sudo: required
service:
   - docker

before_install:
   - docker build -t henhito/docker-react -f Dockerfile.dev .

script:

   - docker run -e CI=true henhito/docker-react npm run test -- --coverage

deploy:
  provider: elacticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-203203670229"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
     secure: $AWS_SECRET_KEY
